name: run_monitor
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: execute py script
        run: |
          python monitor.py
        env:
          email_user: ${{ secrets.email_user }}
          password: ${{ secrets.password }}
          receiver: ${{ secrets.receiver }}